baseURL = "/"
languageCode = "en-us"
title = "Version control through Git, GitHub & GitKraken for researchers"
description = "Workshop materials for RSE Sheffield workshop on 'Version control through Git, GitHub & GitKraken for researchers'"
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Version control through Git, GitHub & GitKraken for researchers"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/annakrystalli/git-github-gitkraken-research"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='far fa-fw fa-copy'></i> Snippets"
url = "/snippets"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = "https://github.com/annakrystalli/git-github-gitkraken-research/edit/main/content/"
  description = "Version control through Git, GitHub & GitKraken for researchers"
  author = "Anna Krystalli"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "rse-learn"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
